import { ScanResult } from '@modelguard/shared';

export function formatMarkdown(result: ScanResult): string {
  const lines: string[] = [];

  lines.push('# ModelGuard Scan Report');
  lines.push('');
  lines.push(`**Directory:** \`${result.directory}\``);
  lines.push(`**Use Case:** ${result.config.useCase}${result.config.mau ? ` (MAU: ${result.config.mau.toLocaleString()})` : ''}`);
  lines.push(`**Scanned:** ${result.timestamp}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Count |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Models found | ${result.summary.totalModels} |`);
  lines.push(`| Compliant | ${result.summary.compliant} |`);
  lines.push(`| Warnings | ${result.summary.warnings} |`);
  lines.push(`| Violations | ${result.summary.violations} |`);
  lines.push('');

  if (result.models.length > 0) {
    lines.push('## Detected Models');
    lines.push('');
    lines.push('| Model | Source | License | File |');
    lines.push('|-------|--------|---------|------|');
    for (const m of result.models) {
      const loc = m.line ? `${m.filePath}:${m.line}` : m.filePath;
      lines.push(`| ${m.name} | ${m.source} | ${m.resolvedLicense ?? 'unknown'} | \`${loc}\` |`);
    }
    lines.push('');
  }

  const errors = result.issues.filter(i => i.severity === 'error');
  const warnings = result.issues.filter(i => i.severity === 'warning');
  const infos = result.issues.filter(i => i.severity === 'info');

  if (errors.length > 0) {
    lines.push('## Violations');
    lines.push('');
    for (const issue of errors) {
      lines.push(`### ❌ ${issue.modelId}`);
      lines.push(`- **License:** ${issue.licenseName}`);
      lines.push(`- **Issue:** ${issue.message}`);
      lines.push(`- **Recommendation:** ${issue.recommendation}`);
      lines.push(`- **File:** \`${issue.line ? `${issue.filePath}:${issue.line}` : issue.filePath}\``);
      lines.push('');
    }
  }

  if (warnings.length > 0) {
    lines.push('## Warnings');
    lines.push('');
    for (const issue of warnings) {
      lines.push(`### ⚠️ ${issue.modelId}`);
      lines.push(`- **License:** ${issue.licenseName}`);
      lines.push(`- **Issue:** ${issue.message}`);
      lines.push(`- **Recommendation:** ${issue.recommendation}`);
      lines.push(`- **File:** \`${issue.line ? `${issue.filePath}:${issue.line}` : issue.filePath}\``);
      lines.push('');
    }
  }

  if (infos.length > 0) {
    lines.push('## Notices');
    lines.push('');
    for (const issue of infos) {
      lines.push(`- **${issue.modelId}:** ${issue.message}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [ModelGuard](https://github.com/timurrakhmatullin/modelguard)*');

  return lines.join('\n');
}
